version: '3.1'
services:
  mycassandra:
    image: cassandra
    container_name: mycassandra
    ports:
      - "9042:9042"
      - "7000:7000"
    volumes:
      - "cassandra-data:/var/lib/cassandra"

volumes:
  cassandra-data: