spring:
  data:
    cassandra:
      port: 9042
      contact-points: localhost
      keyspace-name: shoppingcart
      entity-base-package: com.cassandra.rampup.model
      schema-action: CREATE-IF-NOT-EXISTS
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s
      converters:
        entity-to-udt-packages: com.cassandra.rampup.model
        udt-to-entity-packages: com.cassandra.rampup.CassandraUserTypes
